-- DDL for Note Table

CREATE TABLE NOTE_TABLE(
   ID 				INTEGER PRIMARY KEY AUTOINCREMENT,
   TITLE			VARCHAR(30)      NOT NULL,
   DESCRIPTION      TEXT       NOT NULL,
   LOGIN_ID        	INTEGER,
   CONSTRAINT LOGINID_FK
   FOREIGN KEY (LOGIN_ID) REFERENCES NOTE_LOGIN(LOGIN_ID)
);